# Generated by Django 2.0.8 on 2019-07-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20190529_2023'),
        ('usuarios', '0004_auto_20190520_1717'),
    ]

    operations = [
    ]
