# Generated by Django 2.0.8 on 2019-05-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0028_auto_20190520_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dliquidacion',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='gestionapp.Mliquidacion'),
        ),
    ]
