# Generated by Django 2.0.8 on 2019-05-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0029_auto_20190521_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dliquidacion',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='gestionapp.Dcotizacion'),
        ),
        migrations.DeleteModel(
            name='Mliquidacion',
        ),
    ]
