# Generated by Django 2.0.8 on 2019-07-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0046_auto_20190522_2019'),
        ('gestionapp', '0030_auto_20190522_1508'),
    ]

    operations = [
    ]
